### PR TITLE
sql txt has been updated

### PR DESCRIPTION
**Pull request by UnemployedUncle**
hey

### CODE REVIEW

**Review by tjdrlfdl91 — APPROVED** [review]
good

**Comment by UnemployedUncle** [comment]
plz review this file

**Comment by UnemployedUncle** [comment]
plz make me a reviewer

**Comment by UnemployedUncle** [comment]
I'm waiting for my first merge

**Comment by UnemployedUncle** [comment]
merging sth is a beautiful activity

**Comment by UnemployedUncle** [comment]
hey is there any one home

**Comment by UnemployedUncle** [comment]
who's working in Korea

**Pull request merged**
